### ISSUE TITLE
peak_ratio interval not in data

### ISSUE THREAD

**Issue by katosh** [philipp-baumann/simplerspec#1]
`read_opus_universal` fails for my data around here:
https://github.com/philipp-baumann/simplerspec/blob/af8964160f844ed8544ee196a34fc0517a51bf6d/R/read-opus-universal.R#L294-L301
because there are no `wavenumbers` between 2358 and 2392 in my data, which starts at 3949.511. Why was this specific interval chosen and what is the purpose of the `peak_ratio`? Can I import my data differently?

**Comment by ludensdicereverum** [comment]
Actually (katosh and me) we´re trying to use your package to import OPUS FT-NIR-spectra, the measured spectral range is from 3949 to 11800 per cm. So I´m not that familiar with MIR, but is it some part of a preprocessing calculating the peak_ratio?

**Comment by baumanph** [comment]
Hi katosh and ludensdicereverum, sorry for the late reply. Actually, this is something I need to address because currently the reader is tailored to MIR data. The main reason calculating the peak_ratio is to figure out the type of spectrum. This is a little bit experimental because I'm using the CO2 double peaks that occur in the region between 2358 and 2392 cm^-1. Do you guys have a alternative workaround to figure out the sequence of spectra within an OPUS file?

**Comment by philipp-baumann** [comment]
working on it

**Comment by philipp-baumann** [comment]
soon

**Comment by philipp-baumann** [comment]
Hi katosh and ludensdicereverum,
I got finally the change to spend some time on improving `read_opus_bin_univ()/read_opus_univ()`.
With https://github.com/philipp-baumann/simplerspec/commit/9024e9eab1a1af0278a3155af50f4af295c3e86a , the OPUS reader function should now be able to also read files that only contain FT-NIR spectra. When the mid-IR range from 2302 cm^-1 and 2558 cm^-1 isn't present, the peak ratio of two specific NIR bands at around 5340 cm^-1 (~ 1873 nm) and 5318 cm^-1 is calculated (water vapour). To assign single channel spectra (i.e., sample and reference, "ScSm" and "ScRf"), an empiric threshold of a ratio of smaller than 0.9 is used. This is again a bit a dirty hack, and needs further verification if this works reliably under different environments. I'm thinking of also adding this peak ratio threshold value as function argument so that users can modify.

Another option that I might be planning is to provide a function interface/arguments that allows to specify which spectral blocks are present in files; this requires a-priori knowlege, but might be more robust in comparison to figuring out with current data and some fiddly hacks). 

Would be great if you can confirm whether this works for your spectra, too.
