### ISSUE TITLE
read_opus_univ only extracting SmSc?

### ISSUE THREAD

**Issue by charlotter62** [philipp-baumann/simplerspec#10]
Hello! read_opus_univ() appears to only be extracting the single channel spectrum for particular Bruker opus files, even while specifying extract=c("spc"). The plot below shows a file that correctly extracted the "spc" data (black), and a file where the function extracts just the single channel spectra (red). Both are in this zip file: [example-opus.zip](https://github.com/philipp-baumann/simplerspec/files/5403311/example-opus.zip)
![image](https://user-images.githubusercontent.com/42273530/96478013-2c29b780-1205-11eb-9a7b-16aa87144b2b.png)
Any idea why this might be happening with certain files and how we can adjust the code accordingly?
Thank you!

**Comment by philipp-baumann** [comment]
Hi Charlotte,
thanks for reporting this buggy behavior. This is most likely due to the heuristics used within `read_opus_univ()` to decide on the spectrum type (i.e., single channel reflectance or absorbance). The current heuristics work with the peak ratio around the carbon dioxide absorption (see [read-opus-universal.R](https://github.com/philipp-baumann/simplerspec/blob/master/R/read-opus-universal.R) starting from line 313)
```r
is_mir <- any(sapply(wavenumbers_mir, function(x) length(x) != 0))
    if (isTRUE(is_mir)) {
      # Calculate peak ratio for absorbance at around 2392 cm^(-1)
      # and 2358 cm^(-1)
      peak_ratio <- lapply(
        lapply(names(wavenumbers[notIg]),
          function(i) spc[[i]][wavenumbers[notIg][[i]] < 2392 &
            wavenumbers[notIg][[i]] > 2358]),
        function(j) j[[1]] / j[[length(j)]]
      )
      names(peak_ratio) <- names(spc[notIg])
      # Single channel (Sc) assignment list
      which_Sc <- names(which(peak_ratio > 2))
    } else {
      peak_ratio <- lapply(
        lapply(names(wavenumbers[notIg]),
          function(i) spc[[i]][wavenumbers[notIg][[i]] < 5340 &
            wavenumbers[notIg][[i]] > 5318]),
        function(j) j[[1]] / j[[length(j)]]
      )
      names(peak_ratio) <- names(spc[notIg])
      # Single channel (Sc) assignment list
      which_Sc <- names(which(peak_ratio < 0.9))
    }
```

I always knew it is a bit a dirty hack, but I could not come up with a nice solution that distinguishes spectral block types within proprietary OPUS files at that time. 

Your Vertex 70 or Tensor 27 spectra (will look at the files soon) extend to the NIR, and I guess we might tweak the above control flow for presence of both mid-IR and NIR ranges. 

Another possibility would be that we include a predefined list of which spectra types you expect in your spectra (OPUS software settings where you can chose which spectrum types are stored within OPUS binary files). Would the latter be an option?

Cheers,
Philipp

**Comment by charlotter62** [comment]
Hi Philipp,

Thank you so much for your quick reply! I appreciate you pointing out the
areas of code this is stemming from.

In the past, we have not come across this issue with our instrument, but
have collaborators in New Zealand experiencing it, which is who I reach out
on behalf of. They decided to export the spectral data as .dpt files
instead of opus files as a short term solution.

I also shared the information and suggestions you provided with my PI Jon
Sanderman at the Woodwell Climate Research Center (who I believe you have
collaborated with in the past, or plan to?) since this type of issue will
be important to think about with global spectroscopy initiatives.

Thanks again!

Take care,
Charlotte

**Comment by philipp-baumann** [comment]
Hi @charlotter62 ,it was quite a while ago, but I think now your issue should be solved when you use https://github.com/spectral-cockpit/opusreader2 . It is the successor of opusreader and is ready to use. Thanks for a short confirmation, so that we can close the issue.
