### ISSUE TITLE
read_opus_bin_univ incorrect spc data extraction for some FT-NIRS instruments and not others

### ISSUE THREAD

**Issue by EstherDGoldstein-NOAA** [philipp-baumann/simplerspec#12]
Hello,

I have been using simplerspec to work with OPUS files from Tango and MPAII FT-NIR Bruker instruments. The read_opus_bin_univ function has been working well with the files from the Tango instrument, although there is a small offset on the y-axis absorbance values from the files plotted in OPUS. In contrast, the spectra are not being extracted correctly from the MPAII files. Some peaks are missing or flattened. Looking at plots of the different blocks plotted in OPUS, I'm not sure what the issue is.

1) The MPAII spectra extraction are my major concern. Image of the MPAII plots in OPUS vs spectra extracted from read_opus_bin_univ are attached. 
![image](https://user-images.githubusercontent.com/115666507/203153168-e0968970-cbe5-4e36-84d9-49ab909c1776.png)

2) Any insight regarding the offsets in the y-axis absorbance values from the Tango would also be much appreciated. The offsets occur regardless of whether atm_compminus4offset=TRUE or FALSE. In the examples I'm working with now, the values are ~0.2 absorbance units higher for all spectra and wavenumbers than those plotted in OPUS.

Thank you for any help you can provide!

Esther

**Comment by philipp-baumann** [comment]
Hi Esther,
thanks for reaching out! We have started working on an a novel implementation of the reader. What you describe might be due to an incomplete reverse engineering logic we had before. Your insights could be very valuable for our extended checks we plan to do. Could you test the new opusreader2 https://github.com/spectral-cockpit/opusreader2 and give us feedback in this simplerspec issue, and also open new issue in the opusreader2 repo if it persists? Also, we are planning to include a test suite of OPUS files from different institutes and include those for code testing. Would your institute be willing to share one example OPUS file for each of the instruments? Of course, we would list the institutions and details on the GitHub repo and in vignettes. We plan a CRAN release quite soon.
Cheers,
Philipp

**Comment by EstherDGoldstein-NOAA** [comment]
Thank you Philipp! You seem to have solved the issue in opusreader2. I have also uploaded one Bruker MPAII OPUS file and one Bruker Tango OPUS file.
[opusreader2_check.zip](https://github.com/philipp-baumann/simplerspec/files/10582177/opusreader2_check.zip)

Esther
