### ISSUE TITLE
Error when reading opus file

### ISSUE THREAD

**Issue by blubbercub** [philipp-baumann/simplerspec#2]
When I run read_ops_bin_univ on a spectrum, I get the following error:

Error in { : task 7 failed - "invalid '(to - from)/by'"
In addition: Warning message:
In mapply(FUN = f, ..., SIMPLIFY = FALSE) :
  longer argument not a multiple of length of shorter

Is there a way to check if the file format for my Opus files is different?

**Comment by philipp-baumann** [comment]
Hi blubbercub, 
thanks for reporting. Can you run `traceback()` after the error occurs and report here? Does the error occur only for one file? What is the OPUS software version? What instrument and range (mid-IR, NIR, or combined) are you using? Can you post an example OPUS binary file here?

**Comment by blubbercub** [comment]
Hi Philipp, thanks for looking into this! Here is the result from traceback:

`function (x = NULL, max.lines = getOption("deparse.max.lines")) 
{
    n <- length(x <- .traceback(x))
    if (n == 0L) 
        cat(gettext("No traceback available"), "\n")
    else {
        for (i in 1L:n) {
            xi <- x[[i]]
            label <- paste0(n - i + 1L, ": ")
            m <- length(xi)
            srcloc <- if (!is.null(srcref <- attr(xi, "srcref"))) {
                srcfile <- attr(srcref, "srcfile")
                paste0(" at ", basename(srcfile$filename), "#", 
                  srcref[1L])
            }
            if (is.numeric(max.lines) && max.lines > 0L && max.lines < 
                m) {
                xi <- c(xi[seq_len(max.lines)], " ...")
                m <- length(xi)
            }
            if (!is.null(srcloc)) {
                xi[m] <- paste0(xi[m], srcloc)
            }
            if (m > 1) 
                label <- c(label, rep(substr("          ", 1L, 
                  nchar(label, type = "w")), m - 1L))
            cat(paste0(label, xi), sep = "\n")
        }
    }
    invisible(x)
}
<bytecode: 0x000000000d70a168>
<environment: namespace:base>`

I'm using a Vertex 70 instrument in the MIR, and OPUS 7.5 Build: 7, 5, 18 (20140810). I get the same error on multiple OPUS files; I'm attaching an example.
[20181207_polystyrene_calibration_film.zip](https://github.com/philipp-baumann/simplerspec/files/2672437/20181207_polystyrene_calibration_film.zip)

**Comment by philipp-baumann** [comment]
Hi blubbercub, this is actually the source code of the `traceback()` function and not the call stack of this particular error. I'll have a closer examination of the OPUS file you attached during this week.

**Comment by philipp-baumann** [comment]
Sorry for the delay, I had to concentrate on my core research activities. I'm working on it; I'll give a short summary. I will definitively achieve to implement reading these files. There will probably be another argument that will state which spectra types were saved in the OPUS software, so the user will need to specify that. The order of spectral block types is always consistent, and guess this is not changing with new OPUS versions. Previously, I thought I can distinguish single channel from result spectra by CO2 peak ratios, but this is definitively not ideal because when y units change and different accessories are used, this is not straight-forward. I think maybe this automatic detection what is present should be avoided, and usually one knows which spectral blocks were ticked to be saved. It would be great to see which spectra are saved, but this is the only information I cannot reconstruct from the binary file exploration and the "OPUS programming manual". Maybe this information is encrypted in the header. The present spectra are in transmittance units, and also x units differ, but this is no issue. If anybody is more skilled to hack this last spectral block type info (e.g. Single Channel Sample, Single Channel Reference, Phase Spectrum ...), would be great! I'll soon update the new version, and then you can confirm that it works.

**Comment by philipp-baumann** [comment]
https://github.com/qedsoftware/brukeropusreader 
maybe discuss possible solutions with @tdyczek?

**Comment by philipp-baumann** [comment]
https://github.com/Quasars/orange-spectroscopy/pull/34

**Comment by philipp-baumann** [comment]
github.com/spectral-cockpit/opusreader2 is the recommended way to read OPUS files in R.
